### ISSUE TITLE
Unable to use pixeldata module

### ISSUE THREAD

**Issue by posutsai** [Enet4/dicom-rs#147]
Hi, I have noticed that the repo add submodule pixeldata recently and would like to give it a try. However, I can't import it after specifying dependency in my Cargo.toml.
```toml
[dependencies]
dicom = {version = "0.4.0"}
```
```rust
use dicom::pixeldata // <- compiler complains about not finding pixeldata in dicom
```
After reading the [comment](https://github.com/Enet4/dicom-rs/blob/master/pixeldata/src/lib.rs#L13) in pixeldata/lib.rs, I also tried following configs.

```toml
[dependencies]
dicom_pixeldata = {version = "0.1", default_features = false}
```
This time cargo can't even locate the crate and I can't google for the `pixeldata` crate either. Could you give a hand how to correctly import pixeldata? Thank you very much.

**Comment by Enet4** [comment]
Hello, @posutsai. The `dicom-pixeldata` crate is a recent introduction to the project, and it has not been released yet, nor has it been incorporated into the library parent crate `dicom`. To use it now (although you should know that heavy changes may still happen until it is released) you can depend on the upstream repository.

```toml
[dependencies]
dicom-pixeldata = { git = "https://github.com/Enet4/dicom-rs" }
```

See also #125 to keep track of the progress of this crate.
