### ISSUE TITLE
Latest version fails to build for android

### ISSUE THREAD

**Issue by IsmailAlamKhan** [Enet4/dicom-rs#455]
I am not able to build for android when using the latest version of your package with the following error.

![image](https://github.com/Enet4/dicom-rs/assets/67656229/bd9c05fc-b411-4489-9d7d-a4c86c5388f1)

**Comment by Enet4** [comment]
Thank you for reporting. Please follow the recommendations in issues #432 and #446 so that `openjp2` is excluded from building for that platform. You can also try PR #449.

**Comment by IsmailAlamKhan** [comment]
Hey I am kinda new to rust how can I use the version from your PR?

**Comment by Enet4** [comment]
At your Cargo.toml:

```toml
[dependencies]
dicom = { git = "https://github.com/Enet4/dicom-rs", branch = "change/openjp2-opt" }
```

This also works when fetching individual crates.

See also: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
